#!/bin/sh

# Autostart programs

test -f ~/.Xkeymap && xkbcomp ~/.Xkeymap $DISPLAY
#imwheel &
pkill xcape
xcape -e 'Hyper_L=Tab;Hyper_R=backslash;Control_R=Escape' &

# Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Status bar
$HOME/.config/polybar/launch.sh

# Set brightness to 30
light -S 40

# Wallpaper
~/.fehbg

# Compositor
picom &

# MPD
[ ! -s ~/.config/mpd/pid ] && mpd

# Input method framework
#fcitx5 &

# Change X shpaed cursor on startup
xsetroot -cursor_name left_ptr

# Notification server
#dunst &

# Kill previous xob instances
pkill xob

# Volume bar
tail -f xobvolpipe | xob -s volume &

# Brighness bar
tail -f xobbklpipe | xob -s backlight &

# bspwm config

bspc monitor -d I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX XX

bspc config border_width           3.8
bspc config window_gap             7

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        false
bspc config left_monocle_padding   -7
bspc config right_monocle_padding  -7
bspc config bottom_monocle_padding -7
bspc config focus_follows_pointer  true

# Window Rules
bspc rule -a discord desktop='^3^'
bspc rule -a qBittorrent desktop='^6^'

# Set the border colors.

bspc config focused_border_color      "#100D15"
bspc config active_border_color       "#100D15"
bspc config normal_border_color       "#292928"
bspc config presel_border_color	      "#FFFFFF"
